matrix:
  include:
    - os: linux
      dist: trusty
language: csharp
mono: none
dotnet: 2.1.105
before_install:
  - sudo apt-get install p7zip-full
  - if [ "$REDISTPASSWORD" != "" ] ; then cd Redist ; wget -q https://github.com/surban/managedCuda-redist/releases/download/v9.1.3/redist.7z ; 7z x -p$REDISTPASSWORD -y redist.7z ; fi
script: 
  - unset DOTNET_CLI_TELEMETRY_OPTOUT
  - dotnet build -c Release
  - if [ "$REDISTPASSWORD" != "" ] ; then dotnet pack -c Release ; fi
after_success:
  - dotnet nuget push -s https://api.nuget.org/v3/index.json -k $NUGETKEY 'Packages/Release/*.nupkg' || true 
 